#!/usr/bin/env python3

import json

with open('../../font/font.json') as f:
    font = json.load(f)

remap_from = ''.join(font['remap'].keys())
remap_to = ''.join(font['remap'].values())

font.pop('remap')
index = ''.join(font.keys())

bitmap = bytearray()
map_addr = bytearray()
for glyph in font.values():
    pixels = bytearray.fromhex(glyph)
    ma = (len(pixels)-1) + (len(bitmap)<<3)
    map_addr.append(ma&255)
    map_addr.append(ma>>8)
    bitmap += pixels

with open('font_map_addr.bin', 'wb') as f:
    f.write(map_addr)

with open('font_bitmap.bin', 'wb') as f:
    f.write(bitmap)

with open('font.py', 'w') as f:
    print('remap_from =', remap_from.__repr__(), file=f)
    print('remap_to =', remap_to.__repr__(), file=f)
    print('index =', index.__repr__(), file=f)
    print('with open("font_map_addr.bin", "rb") as f:', file=f)
    print('    map_addr = bytearray(f.read())', file=f)
    print('with open("font_bitmap.bin", "rb") as f:', file=f)
    print('    bitmap = bytearray(f.read())', file=f)
