#!/usr/bin/env python3

import array
import json

with open('../../font/font.json') as f:
    font = json.load(f)

remap_from = ''.join(font['remap'].keys())
remap_to = ''.join(font['remap'].values())

font.pop('remap')
index = ''.join(font.keys())

bitmap = bytearray()
map_addr = array.array('H')
for glyph in font.values():
    pixels = bytearray.fromhex(glyph)
    bitmap += pixels
    ma = len(bitmap)
    map_addr.append(ma)

with open('font.py', 'w') as f:
    print('from array import array', file=f)
    print('remap_from =', remap_from.__repr__(), file=f)
    print('remap_to =', remap_to.__repr__(), file=f)
    print('index =', index.__repr__(), file=f)
    print('map_addr =', map_addr.__repr__(), file=f)
    print('bitmap =', bitmap.__repr__(), file=f)
