#!/usr/bin/env python3

"""
A small utility to convert font to MicroPython-friendly format

Usage:  ./update > font.py
"""

import array
import json

with open('../font/font.json', encoding='utf-8') as f:
    font = json.load(f)

remap_from = ''.join(font['remap'].keys())
remap_to = ''.join(font['remap'].values())

font.pop('remap')
index = ''.join(font.keys())

bitmap = bytearray()
map_addr = array.array('H')
for glyph in font.values():
    pixels = bytearray.fromhex(glyph)
    bitmap += pixels
    ma = len(bitmap)
    map_addr.append(ma)


if __name__ == '__main__':
    print('from array import array')
    print('remap_from =', repr(remap_from))
    print('remap_to =', repr(remap_to))
    print('index =', repr(index))
    print('map_addr =', repr(map_addr))
    print('bitmap =', repr(bitmap))
