#!/usr/bin/env python3

# Setup:
# sudo apt install python3-pyphen hyphen-uk hyphen-en-us

# Usage:
# ./hyphenate < source.txt > target.txt

import sys
import pyphen
import re

hyphenators = [pyphen.Pyphen(lang=l) for l in ('uk_UA', 'en_US')]
word_cut = re.compile(r'([\w\'`]+)')
is_word = re.compile(r'\w')

for line in sys.stdin:
    out = []
    for part in word_cut.split(line.rstrip()):
        if is_word.match(part):
            for dic in hyphenators:
                part = dic.inserted(part)
            out.append(part.replace('-', '\u00ad'))
        else:
            out.append(part)
    print(''.join(out))
